import Head from 'next/head'
import {Inter} from 'next/font/google'
import Homepage from '@/modules/homepage/Homepage'
import QuestionPage from '@/modules/questionpage/QuestionPage'
import ResultModel from '@/modules/resultmodel/ResultModel'

const inter = Inter({subsets: ['latin']})

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Quiz App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Homepage />
      {/* <HtmlQuestionPage /> */}
      {/* <QuestionPage /> */}
      {/* <ResultModel /> */}
    </>
  )
}
